blank_issues_enabled: false
contact_links:
    - name: Question
      url: https://github.com/eamodio/vscode-gitlens/discussions?discussions_q=category%3AQ%26A
      about: Ask and answer questions about GitLens
